param(
  [string]$ServerName = 'rimsage',
  [string]$Runtime = 'node'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repoRoot 'config/mcporter.json'
$outputDir = Join-Path $repoRoot 'tools/generated'
$templatePath = Join-Path $outputDir 'rimsage-cli.ts'
$bundlePath = Join-Path $outputDir 'rimsage-cli.js'

if (-not (Test-Path $configPath)) {
  throw "MCPorter config not found: $configPath"
}

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

$npxCommand = $null
foreach ($candidateName in @('npx.cmd', 'npx')) {
  try {
    $candidate = Get-Command $candidateName -ErrorAction Stop
    if ($candidate.Source) {
      $npxCommand = $candidate.Source
      break
    }
  } catch {
  }
}

if (-not $npxCommand) {
  throw 'npx not found. Install Node.js or run mcporter generate-cli manually.'
}

$arguments = @(
  'mcporter',
  'generate-cli',
  $ServerName,
  '--config',
  $configPath,
  '--output',
  $templatePath,
  '--bundle',
  $bundlePath,
  '--runtime',
  $Runtime,
  '--name',
  'rimsage',
  '--description',
  'RimSage CLI generated by mcporter',
  '--yes'
)

Push-Location $repoRoot
try {
  & $npxCommand @arguments
  if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
  }

  Write-Host "Generated template: $templatePath"
  Write-Host "Generated bundle:   $bundlePath"
} finally {
  Pop-Location
}
